config/routes.rb
# frozen_string_literal: true

# This file tells the Rails server how incoming requests are sent to which
# controller and method.
#
#
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # The root page, e.g. www.example.com/, is sent here
  # root 'controller#method_in_controller'
  root 'home#index'
  # Devise authentification pages. This controlls the user login
  # and authentification system.
  devise_for :users

  # Examples:
  #
  # # Add app CRUD operations from a controller. Used with scaffolding.
  # # CRUD -> create (API/POST), new (page/GET), index, show,
  #           edit(page/GET), update(API/PATCH|PUT), destroy(API/DELETE)
  # resources :my_controller
  #
  # # Add GET path for photos controller, index method
  # get 'photos/index'
  #
  # # Resources, but only register these methods
  # resources :photos, only: [:index, :new, :create, :destroy]
  #
  # # Add PUT path for the given url, but send it to a different controller
  # # than rails would assume by the name. to: 'controller#method_name'.
  # # It would have extected to: 'add_tags#add', which would fail
  # put '/add_tags/add', to: 'users#add_tags'
end

app/models/app_config.rb
# frozen_string_literal: true

# global app configuration model

# Fields:
# - name: string
# - logo_url: string
class AppConfig < ApplicationRecord
  # make sure all fields exist
  validates :name, :logo_url, presence: true

  # make sure app name isn't empty
  # logo can be empty. That's not a big teal tbh.
  validates_length_of :name, minimum: 1
end

app/models/application_record.rb
# frozen_string_literal: true

# Parent class of all models
# Edit to add attributes and behaviors to all models
# TCNJ: You probably won't touch this
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

# Represents a user of the web application
class User < ApplicationRecord
  # Devise is a premade system for managing logins
  # You don't need to do login yourself. It's done for you.
  # TCNJ: don't edit the login system.

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# This is the main controller for the entire project
# Every other controller will inherit from this one
# If there is a behavior or method you want for all controllers,
# it goes here. If that method is a helper, don't add it here,
# but in the helpers folder. They will be avalable in their
# respected views.
class ApplicationController < ActionController::Base
  # If someone tried to pretend to be someone else, an error occurs for them
  protect_from_forgery with: :exception
  # See if the current user is logged in
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller for the home page already made for you
class HomeController < ApplicationController
  # No sign in needed to access these pages
  # Overrides ApplicationController's instructions to check for login by default
  skip_before_action :authenticate_user!

  # GET /
  #
  # This method is empty, yet it works?
  # Rails controller methods can be completely empty and work just fine.
  # It's the name of the method matching to a html.erb file that
  # makes the link between the files.
  # Find me @ app/views/home/index.html.erb
  #
  # Also, any local variable made inside this method will also exist
  # in the view to be displayed. Do not look up information within the
  # view itself. Do it here, please!
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper functions made here are accessable in all views
# for example, app_name is now accessable to all views
module ApplicationHelper
  def app_name
    conf = app_config
    if conf.nil?
      '?'
    else
      conf.name
    end
  end

  private

  def app_config
    AppConfig.first
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Helper methods accessable for views within the home folder
module HomeHelper
end

app/views/home/_erb.html.erb
<h2>ERB basics</h2>
<p>
  <%# You'll notice the tags are in tags. It's because otherwise %>
  <%# they will be parsed as code and I want plain text here. %>
  To run ruby code, put it in a tag formatted like this:
</p>
<p>
  <mark><%% app_name() %></mark> => <mark><% app_name() %></mark>
</p>
<p>
  However, that won't change the HTML sent to the client. In fact, even if
  we tried to write something that we <b>know</b> should show on the page, it
  <b>still</b> won't show up!
</p>
<p>
  <mark><%% 'Hello, world!' %></mark> => <mark><% 'Hello, world!' %></mark>
</p>
<p>
  This is because while rails inputs the return value of 
  a block of code like this into the document, it only does so if we tell
  the language to do so. We do that like this. Add an = to the front of
  the block.
</p>
<p>
  <mark><%%= app_name() %></mark> => <mark><%= app_name() %></mark>
</p>
<p>
  <mark><%%= 'Hello, world!' %></mark> => <mark><%= 'Hello, world!' %></mark>
</p>
<p>
  And success! However, in doing so, we found something important.
  If you want to run some code like an if around HTML depending on if the 
  user is logged in or not, use <mark><%% if %> ... <%% else %> ... <%% end %></mark>.
  None of these tags will output anything since there's no =, so you
  can do things like this. However, if you do want to output something,
  make sure to use the equal sign at the front, or you'll be confused as
  to why nothing is printing!
</p>
<p>
  Oh, and comments are like this. <mark><%%# Hiya! %></mark>. They will not be
  written to the HTML file sent to the user.
</p>
<h2>Writing good html.erb files</h2>
<p>
  Here's the golden rule of erb: don't process data in the erb file!
  There's nothing to stop you from processing information within the view
  itself, but this is very bad practice for several reasons.
</p>
<p>
  The main reason is simple. MVC. Model, View, Controller. A view should
  NOT be fetching its own information or manipulating models. That's the 
  controller's job. Keeping these tasks seperate will make your view
  files highly readable. Speaking from experience, Software Engineering
  projects can become complex due to (unavoidable, you're learning!)
  inexperience with web development and the MVC model. Doing your best to
  follow those guidelines will help you substancially in the last few
  assignments of the classs.
</p>

app/views/home/_filetree.html.erb
<h2>File Structure</h2>
<p>
  The rails file structure is strange. Please be patient. You'll learn it in time.
</p>
<p>
  Note: The following has important sections bolded and underlined. The
  other sections can be largely ignored unless you have some specific need
  for them. <i>Not automatically made</i> means that a brand new rails 
  project will not contain this file. Some things were made to give
  you a starting point for the class.
</p>
<pre>
tcnj-rails-image/app
├── <b><mark>assets (Holds images, CSS, and javascript)</mark></b> 
│   ├── <mark><b>config</b></mark>
│   │   └── <mark><b>manifest.js (how to assemble the things in assets)</b></mark>
│   ├── <mark><b>images (any statically available images)</b></mark>
│   ├── <mark><b>javascripts (Site js [not automatically made])</b></mark>
│   │   └── <mark><b>application.js (global javascript)</b></mark>
│   └── <mark><b>stylesheets</b></mark>
│       ├── <mark><b>application.scss (global css)</b></mark>
│       └── <mark><b>home.scss (controller specific css [not automatically made])</b></mark>
├── channels (Websockets. Almost no-one will use this.)
│   └── application_cable
│       ├── README.md
│       ├── channel.rb
│       └── connection.rb
├── <mark><b>controllers (The C of MVC. Handles data manipulation and handling.)</mark></b>
│   ├── <mark><b>application_controller.rb (Superclass of all controllers)</mark></b>
│   ├── concerns
│   └── <mark><b>home_controller.rb (Controller for the home pages [not automatically made])</mark></b>
├── <mark><b>helpers (Any helper methods wanted inside of erb files)</b></mark>
│   ├── <mark><b>application_helper.rb (Superclass of all helpers</mark></b>
│   └── <mark><b>home_helper.rb (Helpers specific to views within the home folder [not automatically made])</mark></b>
├── javascript (this is webpack specific and will probably be ignored)
│   ├── channels
│   │   ├── consumer.js
│   │   └── index.js
│   └── packs
│       └── application.js
├── <mark><b>jobs (Workloads to be run in the background)</mark></b>
│   └── <mark><b>application_job.rb (Superclass of all jobs)</b></mark>
├── mailers (email systems)
│   └── application_mailer.rb
├── <mark><b>models (The M of MVC, storing and representing information)</mark></b>
│   ├── <mark><b>app_config.rb (A model for strong global settings [not automatically made])</mark></b>
│   ├── <mark><b>application_record.rb (The superclass of all models)</mark></b>
│   ├── concerns
│   └── <mark><b>user.rb (A model representing a website user [not automatically made])</mark></b>
└── <mark><b>views (The V of MVC, defining how information is presented to a user)</mark></b>
    ├── <mark><b>home (Views for the home controller [not automatically made])</mark></b>
    │   ├── _erb.html.erb (A piece of the index page)
    │   ├── _filetree.html.erb (A piece of the index page)
    │   ├── _mvc.html.erb (A piece of the index page)
    │   └── <mark><b>index.html.erb (The webpage you're staring at)</mark></b>
    └── <mark><b>layouts (Special views that contain the common content for all pages)</mark></b>
        ├── <mark><b>application.html.erb (The content displayed on <i>every</i> page)</mark></b>
        ├── mailer.html.erb (The content displayed on all emails using a modern client)
        └── mailer.text.erb (The content displayed on all emails using a <i>very old</i> email clients)
</pre>
</p>

app/views/home/_mvc.html.erb
<h2>The MVC Model of web development</h2>
<p>
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/MVC-Process.svg/400px-MVC-Process.svg.png">
</p>
<p>
  <b>Model:</b> data organization<br>
  <b>View:</b> the presentation of information to the user<br>
  <b>Controller:</b> the manipulation and overseeing of information and access to it
</p>
<p>
  These three categories make up the design of practically every application,
  desktop or internet enabled. It's the seperation of these tasks that
  keeps an application easy to maintain, write, and read. Please make sure
  to understand these categories before working with rails. If you don't 
  recall seeing these terms before, check the class slides.
</p>
<p>
  For more information, see <a href="https://www.wikiwand.com/en/Model%E2%80%93view%E2%80%93controller">Wikipedia</a>.
</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>
  Find me at app/views/home/index.html.erb. Make sure to clear out the file
  before you start working. The other files, _erb, _mvc, _filetree can be deleted.
</p>
<h2>This Template</h2>
<p>
  This rails 6 template will give you a good starting point when working 
  on software engineering projects. The following have already been
  installed and configured...
  <ul>
    <li>Rails 6</li>
    <li>Bootstrap 4. Just add the classes.</li>
    <li>User logins</li>
    <li>Devise user authentication system</li>
    <li><i>better_errors</i> (Better error pages. Seems to not work on the VM.)</li>
    <li><i>web_console</i> (put <mark><%% console %></mark> in a view to have a console on the page)</li>
    <li>A basic layout</li>
  </ul>
</p>
<h2>Devise</h2>
<p>
  Devise is a user authenitification system for ruby on rails designed around
  another program called warden. You will not need to change anything regarding
  its settings unless you are changing login behavior, which is unlikely.
</p>
<p>
  All pages require login by default. The home page has been set to bypass this.
</p>
<p>
  To make a page not require login, add <mark>skip_before_action :authenticate_user!</mark>
  on top of the controller. To limit it to specific methods of a controller,
  tack on <mark>only: ['method_name']</mark> at the end of the line.
  You can add more than one method.
</p>
<h2>Bootstrap</h2>
<p>
  Bootstrap is a CSS and javascript library made by twitter to "bootstrap"
  website development. CSS can be very difficult to work with. Bootstrap
  makes it dramatically easier by giving you an entire library of premade
  classes. If you want to make something look better, bootstrap can
  almost certainly do it without you writing css. For more details,
  <a href="https://getbootstrap.com/docs/4.4/getting-started/introduction/">
    see the documentation</a>.
</p>
<%= render 'mvc' %>
<%= render 'filetree' %>
<%= render 'erb' %>
<h2>Common errors</h2>
<ul>
  <li><b>Pending Migrations:</b> In the console, run <mark>rails db:migrate</mark>. There are databases changes you've written that aren't applied.</li>
  <li><b>Cannot find route for X:</b> The page and action you're trying to do does not exist. Make sure the controller is linked in the routes file, including all nonstandard ones (scaffolding didn't make))</li>
  <li><b>I want to login but don't know password:</b> Default logins are admin@example.com|password and user@example.com|password. If they don't work, see the question mark entry below.</li>
  <li><b>Yarn packages are out of date:</b> In the console, run <mark>yarn install --check-files</mark>. The javascript packages are out of date.</li>
  <li><b>There's a question mark in the top left corner:</b> In the console, run <mark>rails db:reset</mark>. The initial data isn't in the DB.</li>
</ul>
<hr>
<p>
  All in all, use the documentation in this template to your advantage!
  Stack Overflow has tons of resources for ruby on rails and your upperclassmen
  peers can probably give you a hand with rails questions should you need it.
  Plus, if you have a student aid to the class, <i>take advantage of them!</i>
</p>
<p>
  Good luck, and have a great semester!
</p>
<p>
  <i>Ethan Zeigler, '20</i>
</p>
<p class="text-muted" style="font-size: 8pt">
  This template was approved by Pulimood for use in fall 2019. If she says that
  has changed, please let me know and I'll talk with her about what needs to be
  done to fix that.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# Bootstrap meta tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= app_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%# Bootstrap css %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <%# Bootstrap js & dependencies %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%# Navigation Bar %>
    <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
      <a class="navbar-brand" href="#"><%= app_name %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">NavLink</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">A Link</a>
              <a class="dropdown-item" href="#">Another Link</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">And Another</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav">
          <%# If user, show account, else sign in %>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
                Account
              </a>
              <%# Change to rails "link_to" for the actual links when implementing %>
              <%# Make sure to include the css class as shown in the login example %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%# The rails administration panel link %>
                <% if Rails.env.development? %><%= link_to 'Rails Admin', rails_admin_path, class: "dropdown-item" %><% end %>
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <%# Devise requires that the logout command be sent using the 'delete' HTTP verb (method) %>
                <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= button_to "Login", new_user_session_path, class: "btn btn-outline-primary" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <br>
    <br>
    <br>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>